import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kirasky
 */
public class NITK_Social_App extends javax.swing.JFrame {

    /**
     * Creates new form NITK_Social_App
     */
    public NITK_Social_App() {
        initComponents();
    }
    Connection con=null;
    String USER = null;
    Statement stmt=null;
    ResultSet rs=null;
    public void makeConnection(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12391126", "sql12391126", "Mx5G9DXTqv");
            stmt=con.createStatement();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }
    public void breakConnection(){
        try{
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());    
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpFrame = new javax.swing.JFrame();
        signUpUserIDTF = new javax.swing.JTextField();
        signUpUserIdLable = new javax.swing.JLabel();
        signUpPasswordLabel = new javax.swing.JLabel();
        signUpNameTF = new javax.swing.JTextField();
        signUpNameLabel = new javax.swing.JLabel();
        signUpEmailTF = new javax.swing.JTextField();
        signUpEmailLabel = new javax.swing.JLabel();
        signUpIsOrganisationCB = new javax.swing.JCheckBox();
        signUpSignUpLabel = new javax.swing.JLabel();
        signUpWebsiteLabel = new javax.swing.JLabel();
        signUpWebsiteTF = new javax.swing.JTextField();
        signUpSubmitButton = new javax.swing.JButton();
        signUpPasswordField = new javax.swing.JPasswordField();
        loginFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        loginUserIdTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginPasswordPF = new javax.swing.JPasswordField();
        loginIsOrganisationCB = new javax.swing.JCheckBox();
        loginLoginBtn = new javax.swing.JButton();
        profileFrame = new javax.swing.JFrame();
        postDetailsFrame = new javax.swing.JFrame();
        eventsFrame = new javax.swing.JFrame();
        createPostFrame = new javax.swing.JFrame();
        createEventFrame = new javax.swing.JFrame();
        dashboard = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        signUpButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        signUpFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        signUpFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        signUpUserIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpUserIDTFActionPerformed(evt);
            }
        });

        signUpUserIdLable.setText("User ID :");

        signUpPasswordLabel.setText("Password:");

        signUpNameLabel.setText("Name :");

        signUpEmailTF.setText(" ");
        signUpEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpEmailTFActionPerformed(evt);
            }
        });

        signUpEmailLabel.setText(" Email :");

        signUpIsOrganisationCB.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        signUpIsOrganisationCB.setText("Organisation Account");

        signUpSignUpLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        signUpSignUpLabel.setText("Sign Up");

        signUpWebsiteLabel.setText("Website ");

        signUpWebsiteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpWebsiteTFActionPerformed(evt);
            }
        });

        signUpSubmitButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        signUpSubmitButton.setText("Submit ");
        signUpSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpSubmitButtonActionPerformed(evt);
            }
        });

        signUpPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpFrameLayout = new javax.swing.GroupLayout(signUpFrame.getContentPane());
        signUpFrame.getContentPane().setLayout(signUpFrameLayout);
        signUpFrameLayout.setHorizontalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFrameLayout.createSequentialGroup()
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpFrameLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(signUpSubmitButton))
                    .addGroup(signUpFrameLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signUpFrameLayout.createSequentialGroup()
                                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(signUpUserIdLable, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(signUpPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(signUpWebsiteLabel)
                                        .addComponent(signUpEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(signUpNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(signUpEmailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(signUpNameTF)
                                    .addComponent(signUpUserIDTF)
                                    .addComponent(signUpWebsiteTF)
                                    .addComponent(signUpPasswordField)))
                            .addComponent(signUpSignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpIsOrganisationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1193, Short.MAX_VALUE))
        );
        signUpFrameLayout.setVerticalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFrameLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(signUpSignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpNameLabel)
                    .addComponent(signUpNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpUserIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpUserIdLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpPasswordLabel)
                    .addComponent(signUpPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpWebsiteLabel)
                    .addComponent(signUpWebsiteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpEmailTF)
                    .addComponent(signUpEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(signUpIsOrganisationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(signUpSubmitButton)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel2.setText("User ID");

        loginUserIdTF.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        loginUserIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserIdTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel3.setText("Password");

        loginPasswordPF.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N

        loginIsOrganisationCB.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        loginIsOrganisationCB.setText("Organisation Account");
        loginIsOrganisationCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIsOrganisationCBActionPerformed(evt);
            }
        });

        loginLoginBtn.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        loginLoginBtn.setText("Login");
        loginLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1837, Short.MAX_VALUE)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(631, 631, 631)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIsOrganisationCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginPasswordPF)
                            .addComponent(loginUserIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(639, 639, 639))
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(827, 827, 827)
                .addComponent(loginLoginBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFrameLayout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginUserIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loginPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(loginIsOrganisationCB)
                .addGap(55, 55, 55)
                .addComponent(loginLoginBtn)
                .addGap(276, 276, 276))
        );

        profileFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        profileFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout profileFrameLayout = new javax.swing.GroupLayout(profileFrame.getContentPane());
        profileFrame.getContentPane().setLayout(profileFrameLayout);
        profileFrameLayout.setHorizontalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        profileFrameLayout.setVerticalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        postDetailsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        postDetailsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout postDetailsFrameLayout = new javax.swing.GroupLayout(postDetailsFrame.getContentPane());
        postDetailsFrame.getContentPane().setLayout(postDetailsFrameLayout);
        postDetailsFrameLayout.setHorizontalGroup(
            postDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        postDetailsFrameLayout.setVerticalGroup(
            postDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        eventsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eventsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout eventsFrameLayout = new javax.swing.GroupLayout(eventsFrame.getContentPane());
        eventsFrame.getContentPane().setLayout(eventsFrameLayout);
        eventsFrameLayout.setHorizontalGroup(
            eventsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        eventsFrameLayout.setVerticalGroup(
            eventsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        createPostFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createPostFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout createPostFrameLayout = new javax.swing.GroupLayout(createPostFrame.getContentPane());
        createPostFrame.getContentPane().setLayout(createPostFrameLayout);
        createPostFrameLayout.setHorizontalGroup(
            createPostFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1837, Short.MAX_VALUE)
        );
        createPostFrameLayout.setVerticalGroup(
            createPostFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );

        createEventFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createEventFrame.setMaximumSize(new java.awt.Dimension(1837, 1055));
        createEventFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        createEventFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout createEventFrameLayout = new javax.swing.GroupLayout(createEventFrame.getContentPane());
        createEventFrame.getContentPane().setLayout(createEventFrameLayout);
        createEventFrameLayout.setHorizontalGroup(
            createEventFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        createEventFrameLayout.setVerticalGroup(
            createEventFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dashboard.setMinimumSize(new java.awt.Dimension(1837, 1055));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "postID", "Heading", "userID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard.getContentPane());
        dashboard.getContentPane().setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1161, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(615, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to the NITK Social App");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(477, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpButton)
                .addGap(32, 32, 32)
                .addComponent(loginButton)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        signUpFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_loginButtonActionPerformed


    private void signUpUserIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpUserIDTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signUpUserIDTFActionPerformed

    private void signUpEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpEmailTFActionPerformed

    private void signUpWebsiteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpWebsiteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpWebsiteTFActionPerformed

    private void signUpSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpSubmitButtonActionPerformed
        // TODO add your handling code here:
        makeConnection();
        try{
            String name = signUpNameTF.getText();
            String userID = signUpUserIDTF.getText();
            String password = new String(signUpPasswordField.getPassword());
            String emailId = signUpEmailTF.getText();
            String website = signUpWebsiteTF.getText();
            if(signUpIsOrganisationCB.isSelected()){
                //organisaton
                String sql = "Select OrgID FROM Organization where OrgID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "UserID already Present");
                    breakConnection();
                    return;
                }
                //OrgID, Password, Name, EmailID, Website,

                sql = "Insert INTO Organization Values ('"+userID+"','"+password+"','"+name+"','"+emailId+"','"+website+"');";
                stmt.executeUpdate(sql);
            }      
            else{
                String sql = "Select UserID FROM Users where UserID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "UserID already Present");
                    breakConnection();
                    return;
                }
                //OrgID, Password, Name, EmailID, Website,

                sql = "Insert INTO Users Values ('"+userID+"','"+password+"','"+name+"','"+emailId+"','"+website+"');";
                stmt.executeUpdate(sql);
            }
            USER = userID;
            dashboard.setVisible(true);
            signUpFrame.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        breakConnection();
        
    }//GEN-LAST:event_signUpSubmitButtonActionPerformed

    private void signUpPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPasswordFieldActionPerformed

    private void loginUserIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserIdTFActionPerformed

    private void loginIsOrganisationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIsOrganisationCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIsOrganisationCBActionPerformed

    private void loginLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLoginBtnActionPerformed
        // TODO add your handling code here:
        makeConnection();
        try{
            String userID = loginUserIdTF.getText();
            String password = new String(loginPasswordPF.getPassword());
            
            if(loginIsOrganisationCB.isSelected()){
                //organisaton
                String sql = "Select OrgID FROM Organization where OrgID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "UserID is Not Present");
                    breakConnection();
                    return;
                }
                sql = "Select Password FROM Organization where OrgID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                if(!password.equals(rs.getString("Password"))){
                    JOptionPane.showMessageDialog(null, "Password is Incorrect");
                    breakConnection();
                    return;
                }
                
            }
            else{
                //individual
                String sql = "Select UserID FROM Users where UserID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "UserID is Not Present");
                    breakConnection();
                    return;
                }
                sql = "Select Password FROM Users where UserID = '"+userID+"';";
                rs = stmt.executeQuery(sql);
                rs.next();
                if(!password.equals(rs.getString("Password"))){
                    JOptionPane.showMessageDialog(null, "Password is Incorrect");
                    breakConnection();
                    return;
                }
                
                
            }
            USER = userID;
            dashboard.setVisible(true);
            loginFrame.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        breakConnection();
        
    }//GEN-LAST:event_loginLoginBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NITK_Social_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NITK_Social_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NITK_Social_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NITK_Social_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NITK_Social_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame createEventFrame;
    private javax.swing.JFrame createPostFrame;
    private javax.swing.JFrame dashboard;
    private javax.swing.JFrame eventsFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginButton;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JCheckBox loginIsOrganisationCB;
    private javax.swing.JButton loginLoginBtn;
    private javax.swing.JPasswordField loginPasswordPF;
    private javax.swing.JTextField loginUserIdTF;
    private javax.swing.JFrame postDetailsFrame;
    private javax.swing.JFrame profileFrame;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel signUpEmailLabel;
    private javax.swing.JTextField signUpEmailTF;
    private javax.swing.JFrame signUpFrame;
    private javax.swing.JCheckBox signUpIsOrganisationCB;
    private javax.swing.JLabel signUpNameLabel;
    private javax.swing.JTextField signUpNameTF;
    private javax.swing.JPasswordField signUpPasswordField;
    private javax.swing.JLabel signUpPasswordLabel;
    private javax.swing.JLabel signUpSignUpLabel;
    private javax.swing.JButton signUpSubmitButton;
    private javax.swing.JTextField signUpUserIDTF;
    private javax.swing.JLabel signUpUserIdLable;
    private javax.swing.JLabel signUpWebsiteLabel;
    private javax.swing.JTextField signUpWebsiteTF;
    // End of variables declaration//GEN-END:variables
}
